### ISSUE TITLE
Multiline prompt support

### ISSUE THREAD

**Issue by dmeijboom** [rain-1/linenoise-mob#39]
It seems like with this version multiline prompts are working until the screen is cleared using "Ctrl-L". When the user presses this key the cursor is moved to the right. It seems like the padding from the left of the screen is calculated wrong after clearing the screen.

Can this be fixed? Or are multiline prompts (using \n in a prompt) simply not supported?

**Comment by rain-1** [comment]
I tried to reproduce this by changing example.c line 87 to

`    while((line = linenoise("...\n\033[32mこんにちは\x1b[0m> ")) != NULL) {`

but on my system the multiline prompt gets reprinted on the next line each time a key is pressed:

```
...
... にちは> 
こんにちは> 
...
... にちは> 
... にちは> a
... にちは> ay
... にちは> ayy
... にちは> ayya
... にちは> ayyay
... にちは> ayyayy
... にちは> ayyayya
... にちは> ayyayyay
... にちは> ayyayyaya
... にちは> ayyayyayay
こんにちは> ayyayyayay
echo: 'ayyayyayay'
...
こんにちは> 
```

So multiline prompts are broken in a different way here.

It would be good to support them, would you like to implement this?

**Comment by rain-1** [comment]
Googling for linenoise multiline prompt didn't come up with much but made me realize that multiline input - with shift-enter could be useful too.

**Comment by dmeijboom** [comment]
> It would be good to support them, would you like to implement this?

I can definitely take a look.
